# Generated by Django 4.1.5 on 2023-01-13 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfg1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entrepreneur',
        ),
    ]
