# Generated by Django 4.1.5 on 2023-01-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfg1', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=200)),
                ('email1', models.EmailField(max_length=100)),
                ('patent1', models.TextField()),
                ('phone1', models.IntegerField()),
            ],
        ),
    ]
