# Generated by Django 4.1.5 on 2023-01-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfg1', '0004_entrepreneur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innovaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('patent', models.TextField()),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Entrepreneur',
        ),
    ]
