# Generated by Django 4.1.5 on 2023-01-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfg1', '0005_innovaters_delete_entrepreneur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Funder', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
