# Generated by Django 4.1.5 on 2023-01-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfg1', '0006_organisation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Entrepreneur',
        ),
    ]
