# Generated by Django 4.1.5 on 2023-01-29 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfg1', '0007_rename_employee_entrepreneur'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Innovaters',
            new_name='Funders',
        ),
    ]
