# Generated by Django 4.1.5 on 2023-01-29 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gfg1', '0009_rename_organisation_donaters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innovaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfg1.entrepreneur')),
            ],
        ),
    ]
