# Generated by Django 4.1.5 on 2023-01-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfg1', '0010_innovaters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funders',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
